services:
  shmarql:
    build: .
    image: "${SHMARQL_IMAGE:-registry.gitlab.rlp.net/adwmainz/nfdi4culture/knowledge-graph/shmarql/datastories}"
    container_name: "${SHMARQL_CONTAINER_NAME:-shmarql}"
    restart: unless-stopped
    environment:
      - "TZ=Europe/Berlin"
      - "SCHEME=${SHMARQL_SCHEME:-http://}"
      - "DOMAIN=${SHMARQL_DOMAIN:-localhost}"
      - "PORT=7014"
      - "ENDPOINT=http://backend:5000/sparql"
      - "DEBUG=1"
      - "WATCH_DOCS=1"
    volumes:
      - ./stories:/src/docs/course
      - ./navigation.yml:/src/docs/.nav.yml
      - ./mkdocs.yml:/src/mkdocs.yml
      # optional: to persist the built site (first run still needs one build) - can be commented out if not needed
      - ./site:/src/site
    ports:
      - "7015:8000"

  # NEW SERVICE FOR SECURE AI REQUESTS
  backend:
     build: ./backend
     container_name: "llm_backend"
     restart: unless-stopped
     env_file:
       - .env  # Loads the API key from the .env file
     ports:
       - "5001:5000" # Makes the backend accessible on port 5001