PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX cto: <https://nfdi4culture.de/ontology#>
PREFIX n4c: <https://nfdi4culture.de/id/>

SELECT DISTINCT 
  ?artistName
  ?bildindexEntity
  ?bildName
WHERE {
  # 1) alle GND-IDs aus E6077
  ?art cto:elementOf n4c:E6077 ;
      schema:creator ?creatorGND .

  ?creatorGND rdfs:label ?artistName .
  # 2) finde alle Tripel, in denen diese GNDs Objekt sind
  ?bildindexEntity ?predicate ?creatorGND .

  # 3) filtere nur die Subjects, die auf bildindex.de verweisen
  FILTER regex(str(?bildindexEntity), "https?://(www\\.)?bildindex\\.de/")

  # 4) show the name of the artwork
  ?bildindexEntity rdfs:label ?bildName .
}
ORDER BY ?creatorGND ?bildindexEntity
LIMIT 999