PREFIX schema1: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX cto: <https://nfdi4culture.de/ontology#>
PREFIX n4c: <https://nfdi4culture.de/id/>

SELECT ?building (COUNT(?subject) AS ?count)
WHERE {
  ?subject rdf:type schema1:LandmarksOrHistoricalBuildings ;
           cto:subjectConcept ?concept ;
           cto:elementOf n4c:E6077 .

  VALUES (?concept ?building) {
    (<http://www.wikidata.org/entity/Q317557> "Pfarrkirche")
    (<http://www.wikidata.org/entity/Q108325> "Kapelle")
    (<http://www.wikidata.org/entity/Q1436181> "Lustschloss")
    (<http://www.wikidata.org/entity/Q1424449> "Jagdschloss")
    (<http://www.wikidata.org/entity/Q607241> "Pfarrhaus")
    (<http://www.wikidata.org/entity/Q57661959> "Gartenpavillon")
    (<http://www.wikidata.org/entity/Q480226> "Amtshaus")
    (<http://www.wikidata.org/entity/Q879050> "Herrenhaus / Rittersitz / Gutshof / Hofmark / Häuptlingssitz")
    (<http://www.wikidata.org/entity/Q16970> "Kirche")
    (<http://www.wikidata.org/entity/Q62098579> "Schlosskirche")
    (<http://www.wikidata.org/entity/Q61726887> "Hofkirche")
    (<http://www.wikidata.org/entity/Q57660343> "Konzerthaus / Theater / Oper / Komödienhaus")
    (<http://www.wikidata.org/entity/Q952885> "Orangerie")
    (<http://www.wikidata.org/entity/Q53536964> "Residenz")
    (<http://www.wikidata.org/entity/Q1021106> "Bürgerhaus / Patrizierhaus")
    (<http://www.wikidata.org/entity/Q7743> "Wohnhaus")
    (<http://www.wikidata.org/entity/Q53536964> "Schloss")
    (<http://www.wikidata.org/entity/Q5787273> "Gartengut")
    (<http://www.wikidata.org/entity/Q5302681> "Witwensitz")
    (<http://www.wikidata.org/entity/Q55496607> "Klosterkirche")
    (<http://www.wikidata.org/entity/Q12292478> "Wohn- und Arbeits-/Geschäftshaus")
    (<http://www.wikidata.org/entity/Q3044808> "Nebengebäude")
    (<http://www.wikidata.org/entity/Q25550691> "Rathaus -> sonstige Stadt")
    (<http://www.wikidata.org/entity/Q1783234> "Wohn- und Amtshaus")
    (<http://www.wikidata.org/entity/Q5787273> "Gartenhaus")
    (<http://www.wikidata.org/entity/Q25550691> "Rathaus -> Freie Stadt / Reichsstadt")
    (<http://www.wikidata.org/entity/Q1015103> "Kapelle -> Schlosskapelle")
    (<http://www.wikidata.org/entity/Q15848826> "Nebenresidenz")
    (<http://www.wikidata.org/entity/Q856584> "Bibliothek")
    (<http://www.wikidata.org/entity/Q1802963> "Apanagesitz")
    (<http://www.wikidata.org/entity/Q25047790> "Kapitänshaus")
    (<http://www.wikidata.org/entity/Q16884952> "Landhaus")
    (<http://www.wikidata.org/entity/Q1686006> "Sommerresidenz")
    (<http://www.wikidata.org/entity/Q83405> "Produktionsstätte")
    (<http://www.wikidata.org/entity/Q751876> "Landschloss")
    (<http://www.wikidata.org/entity/Q1202402> "Stadthaus -> Adelspalais (in der Stadt)")
    (<http://www.wikidata.org/entity/Q10531620> "Vogtei")
    (<http://www.wikidata.org/entity/Q489357> "Bauernhaus")
    (<http://www.wikidata.org/entity/Q489357> "Bad")
    (<http://www.wikidata.org/entity/Q115958827> "Karitative Einrichtung")
    (<http://www.wikidata.org/entity/Q1007870> "Sammlungsbau")
    (<http://www.wikidata.org/entity/Q1412205> "Zeughaus")
    (<http://www.wikidata.org/entity/Q1457501> "Friedhofskapelle")
    (<http://www.wikidata.org/entity/Q57778855> "Brauerei")
    (<http://www.wikidata.org/entity/Q276173> "Pavillon")
    (<http://www.wikidata.org/entity/Q334383> "Abteikirche")
    (<http://www.wikidata.org/entity/Q256020> "Gastwirtschaft / Schänke / Herberge / Hotel")
    (<http://www.wikidata.org/entity/Q816265> "Belvedere")
    (<http://www.wikidata.org/entity/Q16884952> "")
    (<http://www.wikidata.org/entity/Q1434544> "Kommende / Komturei")
    (<http://www.wikidata.org/entity/Q39364723> "Karitative Einrichtung -> Spital / Hospital")
    (<http://www.wikidata.org/entity/Q481289> "Schloss -> Residenz -> Hauptresidenz")
    (<http://www.wikidata.org/entity/Q1509716> "Stiftskirche")
    (<http://www.wikidata.org/entity/Q1135108> "Corps de Logis")
    (<http://www.wikidata.org/entity/Q62050886> "Kavaliershaus")
    (<http://www.wikidata.org/entity/Q999354> "Freihof / Freihaus")
    (<http://www.wikidata.org/entity/Q879050> "Hauptgebäude")
    (<http://www.wikidata.org/entity/Q114500877> "Apotheke")
    (<http://www.wikidata.org/entity/Q1940809> "Versammlungshaus")
    (<http://www.wikidata.org/entity/Q11691> "Börse")
    (<http://www.wikidata.org/entity/Q488444> "Anatomie")
    (<http://www.wikidata.org/entity/Q2085381> "Verlagshaus")
    (<http://www.wikidata.org/entity/Q25550691> "Rathaus")
    (<http://www.wikidata.org/entity/Q33092688> "Eremitage")
    (<http://www.wikidata.org/entity/Q160645> "Karitative Einrichtung -> Waisenhaus")
    (<http://www.wikidata.org/entity/Q1244442> "Schule")
    (<http://www.wikidata.org/entity/Q1793095> "Kuriengebäude")
  }
}
GROUP BY ?building
ORDER BY DESC(?count)